export const restaurants = [
    'The Sour Merchant',
    'The Island Hog',
    'The Summer Empress',
    'The Cocoa Block',
    'The Silent Clam',
    'Bounty',
    'The Lamb',
    'The Pearl',
    'Roots',
    'Bonds',
    'Fare & Feed',
    'Golden Palace',
    'Soups & Snacks',
    'Quick Bite',
    'Fast & Friendly',
    'Big Bites',
    'Blind Pig',
    'Eatable',
    'Eatery',
    'Goodies',
    'Lard Boy',
    'Many Foods',
    'Me Likey',
    'Wonton Express'
];

export const menuItems = [
    'Braised Sweet \'n Sour Lamb',
    'Barbecued Dark Ale Quail',
    'Sautéed Light Ale Crab',
    'Stuffed Rosemary Cod',
    'Fire-Grilled Light Ale Flatbread',
    'Fried Savory Tofu',
    'Gooseberry and White Chocolate Toffee',
    'Walnut and Raspberry Strudel',
    'Coconut Snacks',
    'Grape Bombe',
    'Oven-Grilled Potatoes & Mammoth',
    'Basted Lime Quail',
    'Breaded Lime & Ginger Lobster',
    'Broasted Mango & Pine Cod',
    'Barbecued Sour & Cream Pizza',
    'Sautéed Wasabi Bread',
    'Pecan and Blueberry Strudel',
    'Mango and Blueberry Gingerbread',
    'Honey Tarte Tatin',
    'Grapefruit Tarte Tatin'
];

export const deliveryTimes = [
    '11:45',
    '12:00',
    '12:15',
    '12:30',
    '12:45'
]

export const addresses = [
    '5669 Oakglen Dr, Burnaby, BC V5H 3M4',
    '1980 Sasamat Pl, Vancouver, BC V6R 4A3',
    '2050 Nelson St, Vancouver, BC V6G 1N6',
    '6329 Angus Dr, Vancouver, BC V6M 3P4',
    '6632 Hampton Blvd E, Surrey, BC V3W 1N2',
    '4669 Drummond Dr, Vancouver, BC V6R 1E8',
    '4193 St George St, Vancouver, BC V5V 4A2',
    '1445 14th Ave W, Vancouver, BC V6H 1R5',
    '1515 2nd Ave W, Vancouver BC V6J 5C5',
    '1601 Barclay St, Vancouver, BC V6G 1J9',
    '2837 6th Ave W, Vancouver, BC V6K 1X2',
    '4333 Cliffmont Rd, North Vancouver, BC V7G 1J6',
    '2134 6th Ave W, Vancouver, BC V6K 1V6',
    '1207 Redwood St, North Vancouver, BC V7P 2V4',
    '1487 27th Ave E, Vancouver, BC V5N 2W6',
    '7544 Main St, Vancouver, BC V5X 3J9',
    '2799 Yew St, Vancouver, BC V6K 4W2',
    '272 Newdale Crt, North Vancouver, BC V7N 3H1',
    '1175 Broughton St, Vancouver, BC V6G 3K9',
    '131 4th St W, North Vancouver, BC V7M 3C8',
    '6043 Gleneagles Close, West Vancouver ,BC V7W 3G5'
]

export const companies = [
    'Hauck Group',
    'Pacocha LLC',
    'Stanton, Sipes and Zieme',
    'Feeney - Dickens',
    'Herman, Crist and Turcotte',
    'Haag Inc',
    'DuBuque, Roob and Kreiger',
    'Macejkovic, Effertz and Fadel',
    'Hirthe Inc',
    'Goodwin Group',
    'Mertz - Conroy',
    'Mitchell, Turcotte and Heathcote',
    'Hermann - Mohr',
    'Mertz, Gleason and Schinner',
    'Lakin - Braun',
    'Ziemann and Sons',
    'Bauch LLC',
    'Howe Inc',
    'Muller - Spinka',
    'Will - Ledner',
    'Gleichner, Koss and Rosenbaum',
    'Beier LLC',
    'Schultz - Greenholt',
    'Cormier, Purdy and Goldner',
    'Johnson LLC',
    'Glover - Steuber',
    'Vandervort Group',
    'Ankunding - Stehr',
    'Kuhn - Hoeger',
    'Quitzon, Treutel and O\'Hara',
];